// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createMockClient() {
  const tables: Record<string, any[]> = {
    participants: [],
    selections: [],
    game_state: [{ id: crypto.randomUUID(), current_card_index: -1, updated_at: new Date().toISOString() }],
  };

  const mockChannel = {
    on: () => mockChannel,
    subscribe: () => mockChannel,
    unsubscribe: () => {},
  };

  function queryBuilder(table: string) {
    let _filters: Array<{ col: string; val: any; op: string }> = [];
    let _insertData: any = null;
    let _updateData: any = null;
    let _isDelete = false;
    let _isSingle = false;
    let _selectCols: string | null = null;
    let _limit: number | null = null;

    const chain: any = {
      select: (cols?: string) => { _selectCols = cols ?? "*"; return chain; },
      insert: (data: any) => { _insertData = Array.isArray(data) ? data : [data]; return chain; },
      update: (data: any) => { _updateData = data; return chain; },
      delete: () => { _isDelete = true; return chain; },
      eq: (col: string, val: any) => { _filters.push({ col, val, op: "eq" }); return chain; },
      neq: (col: string, val: any) => { _filters.push({ col, val, op: "neq" }); return chain; },
      limit: (n: number) => { _limit = n; return chain; },
      single: () => { _isSingle = true; return chain; },
      then: (resolve: any, reject?: any) => {
        try {
          const result = execute();
          resolve(result);
        } catch (e) {
          if (reject) reject(e); else throw e;
        }
      },
    };

    function matchesFilters(row: any) {
      return _filters.every(f => {
        if (f.op === "neq") return row[f.col] !== f.val;
        return row[f.col] === f.val;
      });
    }

    function execute() {
      if (!tables[table]) tables[table] = [];

      if (_insertData) {
        const rows = _insertData.map((item: any) => ({
          id: crypto.randomUUID(),
          created_at: new Date().toISOString(),
          ...item,
        }));
        tables[table].push(...rows);
        const data = _isSingle ? rows[0] : rows;
        return { data, error: null };
      }

      if (_updateData) {
        tables[table] = tables[table].map(row =>
          matchesFilters(row) ? { ...row, ..._updateData } : row
        );
        return { data: tables[table].filter(matchesFilters), error: null };
      }

      if (_isDelete) {
        tables[table] = tables[table].filter(row => !matchesFilters(row));
        return { data: null, error: null };
      }

      // select
      let filtered = _filters.length > 0
        ? tables[table].filter(matchesFilters)
        : [...tables[table]];
      if (_limit !== null) filtered = filtered.slice(0, _limit);
      const data = _isSingle ? (filtered[0] ?? null) : filtered;
      return { data, error: null };
    }

    return chain;
  }

  return {
    from: (table: string) => queryBuilder(table),
    channel: () => mockChannel,
    removeChannel: () => {},
  } as any;
}

export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMockClient();